version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    networks:
      - fullstack-chatapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: full-stack_backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
      - JWT_SECRET=Ankit@2026!SecureJWTKey#8xP4mN7qL2zR9tV
      - PORT=5001
    depends_on:
      - mongodb
    networks:
      - fullstack-chatapp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: full-stack_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fullstack-chatapp

networks:
  fullstack-chatapp:
    driver: bridge

volumes:
  mongo-data:
